/*
 * Generated by the Waxeye Parser Generator - version 0.8.1
 * www.waxeye.org
 */
package ru.morpher;

/**
 * The types of AST nodes.
 *
 * @author Waxeye Parser Generator
 */
public enum ZalType
{
    _Empty,
    _Char,
    _Pos,
    _Neg,
    Entry,
    StressInfo,
    NoStress,
    NormallyNoStress,
    Defs,
    HomoNum,
    Number,
    Headword,
    Def,
    See_also,
    Examples,
    Example,
    Multiword_index,
    Index_variants,
    Plus,
    Idioms,
    Idiom,
    Irregular_forms,
    Irregular_form,
    Irregular_plural_gen,
    Forms,
    Form,
    Style,
    Old,
    Folksy,
    Prof,
    Alt_lemma,
    See,
    Comma,
    Extras,
    Extra,
    Paragraph,
    No_plural_genitive,
    Difficult_plural_genitive,
    Difficult_plural,
    Yo,
    Index_node,
    Index0,
    Index,
    CircledNumbers,
    CircledNumberOpt,
    CircledNumberOptional,
    CircledNumber,
    Angle_index,
    Symbols,
    Symbol,
    Index_number,
    Scheme,
    Comment,
    Ws,
    LETTER,
    STRESS_MARK,
    NewLine
}
