/*
 * Generated by the Waxeye Parser Generator - version 0.8.1
 * www.waxeye.org
 */
package ru.morpher;

/**
 * The types of AST nodes.
 *
 * @author Waxeye Parser Generator
 */
public enum ZalType
{
    _Empty,
    _Char,
    _Pos,
    _Neg,
    Entry,
    StressInfo,
    NoStress,
    NormallyNoStress,
    Defs,
    HomoNum,
    Number,
    Headword,
    Def,
    Index_sep,
    Slash_slash,
    Plus,
    Idioms,
    Idiom,
    Irregular_forms,
    Irregular_form,
    Irregular_plural_gen,
    Forms,
    Form,
    Old,
    Alt_lemma,
    Comma,
    Extras,
    Extra,
    Difficult_plural_genitive,
    Difficult_plural,
    Index,
    Main_symbol,
    Index_number,
    Scheme,
    Comment,
    Ws,
    LETTER,
    STRESS_MARK,
    NewLine
}
